### ISSUE TITLE
I get HTTP 400 error, after setup the ratticdb server

### ISSUE THREAD

**Issue by Gary-Hui** [ptman/rattic-docker#2]
After setup the ratticdb server, i use chrome to open the below url:
http://192.168.56.126:8000,then I got 400 error

PS:192.168.56.126 is the host server which the ratticdb docker is run.

**Comment by Gary-Hui** [comment]
Below is the nginx log：
nginx_1     | 192.168.56.1 - nagiosadmin [19/Jun/2017:18:25:36 +0000] "GET / HTTP/1.1" 400 37 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" "-"

**Comment by ptman** [comment]
Did you follow the docker-compose steps outlined in the readme? I just tried and it worked for me.

**Comment by ptman** [comment]
Cannot reproduce, works for me.
